-- Delivery ledger for automatic WhatsApp recommendation campaigns.
-- Apply once in Supabase before setting WHATSAPP_BROADCAST_TEMPLATE.
create table if not exists public.whatsapp_marketing_subscribers (
  customer_phone text primary key,
  status text not null default 'subscribed' check (status in ('subscribed', 'unsubscribed')),
  consent_source text not null,
  consent_recorded_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.whatsapp_marketing_subscribers enable row level security;
-- No public policies: consent must be written by a trusted server/admin flow.

create table if not exists public.whatsapp_campaign_deliveries (
  id bigint generated by default as identity primary key,
  campaign_key text not null,
  customer_phone text not null,
  template_name text not null,
  status text not null check (status in ('sent', 'failed')),
  error text,
  product_url text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (campaign_key, customer_phone)
);

create index if not exists whatsapp_campaign_deliveries_phone_created_idx
  on public.whatsapp_campaign_deliveries (customer_phone, created_at desc);

alter table public.whatsapp_campaign_deliveries enable row level security;
-- No public policies: only the Supabase service role used by Netlify can read/write.
